services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes-api
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-123456}
      DB_PORT: ${DB_PORT:-5432}
    ports:
      - "8000:8000"
