CREATE TABLE IF NOT EXISTS diabetes_table (
    id SERIAL PRIMARY KEY,
    pregnancies DOUBLE PRECISION NOT NULL,
    glucose DOUBLE PRECISION NOT NULL,
    bloodpressure DOUBLE PRECISION NOT NULL,
    bmi DOUBLE PRECISION NOT NULL,
    diabetespedigreefunction DOUBLE PRECISION NOT NULL,
    age DOUBLE PRECISION NOT NULL,
    outcome INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
